modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="vsie"
version="0.0.1"
displayName="VS:Interstellar_Expansion"
logoFile="icon.png"
authors="kodu16"
modClass="com.kodu16.vsie.vsie"

description='''Interstellar!'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="[0.5.1.a,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId = "valkyrienskies"
mandatory = true
versionRange = "(,2.4.0)"
ordering = "AFTER"
side = "BOTH"

[[mod.natives]]
module = "lwjgl-sdl"
os = "WINDOWS"
arch = "x86_64"
path = "natives/windows"